"""
OpenInterview - 面试报告生成服务

职责：为「面试完毕(status=3)」的面试调用 LLM 评估 → 渲染 PDF → 存库，状态置为 4。
"""
from datetime import datetime

from jinja2 import Environment
from weasyprint import HTML

from config import config
from constants import QUESTION_FULL_SCORE, InterviewStatus
from database import get_db
from services.llm import chat_json


def call_ai_model(candidate_name, position_name, interviewer, questions) -> dict:
    """调用 LLM 对每个问题评分并给出综合评价，失败时返回空评估占位"""
    prompt = (
        f'你是一位专业的面试评估专家，需要对候选人"{candidate_name}"'
        f'应聘"{position_name}"职位的面试表现进行评估。面试官是 {interviewer}。\n\n'
        "请根据以下面试问题、评分标准和候选人的回答，对每个问题进行评分和点评，并给出综合评价。\n"
        f"注意：每个问题评分范围是 0-{QUESTION_FULL_SCORE} 分，综合评分范围也是 0-{QUESTION_FULL_SCORE} 分。\n\n"
    )
    for i, q in enumerate(questions, 1):
        prompt += (
            f"问题{i}: {q.get('question', '未提供问题')}\n"
            f"评分标准: {q.get('score_standard', '未提供评分标准')}\n"
            f"候选人回答: {q.get('answer_text') or '未提供回答'}\n\n"
        )

    prompt += (
        "请以 JSON 格式返回评估结果，包含：\n"
        "1. question_evaluations: 每个问题的评分和评价（id, question, score_standard, answer, score, comments）\n"
        f"2. technical_score: 技术能力总分(0-{QUESTION_FULL_SCORE})\n"
        f"3. communication_score: 沟通能力总分(0-{QUESTION_FULL_SCORE})\n"
        f"4. overall_score: 综合评分(0-{QUESTION_FULL_SCORE})\n"
        "5. comments: 面试官评语（综合评价候选人的优缺点）\n"
        "6. recommendation: 录用建议（推荐录用/可以考虑/不建议录用）\n"
    )

    try:
        return chat_json(
            "你是一位专业的面试评估专家，负责评估技术面试表现。",
            prompt,
        )
    except Exception as e:
        print(f"[report] 调用 LLM 失败: {e}")
        return {}


def generate_pdf_report(candidate_name, position_name, interviewer, evaluation_result) -> bytes:
    """渲染 HTML 模板并转换为 PDF"""
    html_template = """
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>面试报告</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .container { max-width: 800px; margin: auto; }
            .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; }
            .section { margin-top: 20px; }
            .section h2 { color: #2c3e50; }
            .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
            .table th, .table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            .table th { background-color: #f2f2f2; }
            .question-section { border: 1px solid #ddd; padding: 15px; margin-bottom: 15px; border-radius: 5px; }
            .question-title { font-weight: bold; color: #2c3e50; }
            .score { font-weight: bold; color: #e74c3c; }
            .footer { margin-top: 30px; text-align: center; color: #7f8c8d; }
        </style>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>面试报告</h1>
                <p>{{ interview_date }}</p>
            </div>
            <div class="section">
                <h2>候选人信息</h2>
                <table class="table">
                    <tr><th>姓名</th><td>{{ candidate_name }}</td></tr>
                    <tr><th>应聘职位</th><td>{{ position }}</td></tr>
                    <tr><th>面试官</th><td>{{ interviewer }}</td></tr>
                </table>
            </div>
            <div class="section">
                <h2>面试评估</h2>
                <table class="table">
                    <tr><th>技术能力</th><td>{{ technical_score }}/100</td></tr>
                    <tr><th>沟通能力</th><td>{{ communication_score }}/100</td></tr>
                    <tr><th>综合评分</th><td>{{ overall_score }}/100</td></tr>
                </table>
            </div>
            <div class="section">
                <h2>面试官评语</h2>
                <p>{{ comments }}</p>
            </div>
            <div class="section">
                <h2>推荐意见</h2>
                <p>{{ recommendation }}</p>
            </div>
            <div class="section">
                <h2>问题评估详情</h2>
                {% for q in question_evaluations %}
                <div class="question-section">
                    <p class="question-title">问题{{ loop.index }}: {{ q.question }}</p>
                    <p><strong>评分标准:</strong> {{ q.score_standard }}</p>
                    <p><strong>候选人回答:</strong> {{ q.answer }}</p>
                    <p><strong>评分:</strong> <span class="score">{{ q.score }}/100</span></p>
                    <p><strong>点评:</strong> {{ q.comments }}</p>
                </div>
                {% endfor %}
            </div>
            <div class="footer">
                <p>Generated by OpenInterview</p>
            </div>
        </div>
    </body>
    </html>
    """

    render_data = {
        "interview_date": datetime.now().strftime("%Y年%m月%d日"),
        "candidate_name": candidate_name,
        "position": position_name,
        "interviewer": interviewer,
        "technical_score": evaluation_result.get("technical_score", "-"),
        "communication_score": evaluation_result.get("communication_score", "-"),
        "overall_score": evaluation_result.get("overall_score", "-"),
        "comments": evaluation_result.get("comments", "评估生成失败，请人工复核"),
        "recommendation": evaluation_result.get("recommendation", "-"),
        "question_evaluations": evaluation_result.get("question_evaluations", []),
    }

    env = Environment()
    template = env.from_string(html_template)
    rendered = template.render(**render_data)
    return HTML(string=rendered).write_pdf()


def update_interview_report(interview_id: int, report_content: bytes) -> None:
    """保存报告并更新状态为「报告已生成」"""
    conn = get_db()
    try:
        conn.execute(
            "UPDATE interviews SET report_content = ?, status = ? WHERE id = ?",
            (report_content, int(InterviewStatus.REPORT_GENERATED), interview_id),
        )
        conn.commit()
    finally:
        conn.close()


def process_pending_reports() -> None:
    """扫描所有「面试完毕」的面试，逐一生成报告（单场失败不影响其他场次）"""
    print(f"[report] [{datetime.now():%Y-%m-%d %H:%M:%S}] 检查需要生成报告的面试...")

    conn = get_db(row_factory=True)
    interviews = [dict(r) for r in conn.execute(
        "SELECT id, candidate_id, interviewer FROM interviews WHERE status = ?",
        (int(InterviewStatus.COMPLETED),),
    ).fetchall()]
    conn.close()

    if not interviews:
        print("[report] 暂无需要生成报告的面试")
        return

    print(f"[report] 找到 {len(interviews)} 场待评估面试")

    for interview in interviews:
        interview_id = interview["id"]
        try:
            conn = get_db(row_factory=True)
            candidate = conn.execute(
                "SELECT id, name, position_id FROM candidates WHERE id = ?",
                (interview["candidate_id"],),
            ).fetchone()
            conn.close()
            if not candidate:
                print(f"[report] 找不到候选人 {interview['candidate_id']}，跳过")
                continue

            conn = get_db(row_factory=True)
            position = conn.execute(
                "SELECT id, name FROM positions WHERE id = ?",
                (candidate["position_id"],),
            ).fetchone()
            questions = [dict(r) for r in conn.execute(
                "SELECT * FROM interview_questions WHERE interview_id = ?", (interview_id,)
            ).fetchall()]
            conn.close()
            if not position:
                print(f"[report] 找不到岗位 {candidate['position_id']}，跳过")
                continue

            evaluation = call_ai_model(
                candidate["name"], position["name"], interview["interviewer"], questions
            )
            pdf_report = generate_pdf_report(
                candidate["name"], position["name"], interview["interviewer"], evaluation
            )
            update_interview_report(interview_id, pdf_report)
            print(f"[report] 面试 {interview_id}（{candidate['name']}）报告已生成")
        except Exception as e:
            print(f"[report] 处理面试 {interview_id} 失败: {e}")
